# Generated by Django 2.2.5 on 2019-09-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de Receta')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_guardada', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Momento de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Momento de edicion')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Las recetas',
                'ordering': ['-created'],
            },
        ),
    ]
