# Generated by Django 2.2.5 on 2019-09-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_auto_20190917_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='image',
        ),
        migrations.AddField(
            model_name='receta',
            name='imageC',
            field=models.ImageField(blank=True, null=True, upload_to='img_receta_guardada', verbose_name='Imagen Chica'),
        ),
        migrations.AddField(
            model_name='receta',
            name='imageG',
            field=models.ImageField(blank=True, null=True, upload_to='img_receta_guardada', verbose_name='Imagen Grande'),
        ),
    ]
