# Generated by Django 2.2.5 on 2019-09-17 18:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_auto_20190917_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
