# Generated by Django 2.2.5 on 2019-09-19 14:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprendimientos', '0005_auto_20190918_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_emprendimientos', verbose_name='Imagen')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace o Iframe')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Momento de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Momento de edicion')),
                ('categories', models.ManyToManyField(related_name='get_post', to='emprendimientos.Categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Informacion',
                'ordering': ['-created'],
            },
        ),
    ]
