# Generated by Django 2.2.5 on 2019-09-18 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de categoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Momento de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Momento de edicion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de Receta')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_emprendimientos', verbose_name='Imagen')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Momento de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Momento de edicion')),
                ('categories', models.ManyToManyField(to='emprendimientos.Categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Emprendimiento',
                'verbose_name_plural': 'Emprendimientos',
                'ordering': ['-created'],
            },
        ),
    ]
