# Generated by Django 2.2.5 on 2019-09-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='url_iframe',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace Iframe'),
        ),
    ]
