# Generated by Django 2.2.5 on 2019-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimientos', '0002_emprendimiento_url_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='url_iframe',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Enlace Iframe'),
        ),
    ]
