# Generated by Django 2.2.5 on 2019-09-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimientos', '0003_auto_20190918_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='categories',
            field=models.ManyToManyField(related_name='get_posts', to='emprendimientos.Categoria', verbose_name='Categorias'),
        ),
    ]
